### ISSUE TITLE
Rendering problems on Chrome - overlapping characters and not readable letters in default view

### ISSUE THREAD

**Issue by PawelW13i** [mozilla/pdf.js#14641]
PDF file: [0939bfa0-731d-48ca-8c0b-ea110cdcf143.pdf](https://github.com/mozilla/pdf.js/files/8197957/0939bfa0-731d-48ca-8c0b-ea110cdcf143.pdf)

Configuration:
- Web browser and its version:
  Works fine on: Firefox - 97.0.2 (64 bity) 
  Problem noticed on: Chrome 99.0.4844.51 (and lower)
- Operating system: Windows
- PDF.js version: latest (currently v2.13.216)

Steps to reproduce the problem:
1. Try to open attached PDF in Chrome (and in Firefox)
2. Check the "footer" - telephone, bankgiro and other words are not fully visible on Chrome

What is the expected behavior? (add screenshot) 
![Firefox](https://user-images.githubusercontent.com/101097553/157042983-1e9f93a3-d9ae-4823-972c-191b008728e6.png)

What went wrong? (add screenshot)
![Chrome](https://user-images.githubusercontent.com/101097553/157042980-5c09b9cc-f008-4bbb-8b58-4abd63da0444.png)

Problem was not spotted in version 2.7.570

One extra finding done recently - problem occurs on some subset of PDF's and they are coming from one "provider" - ABBY FineReader Engine 12
![abby](https://user-images.githubusercontent.com/101097553/169555036-de9776d2-63d2-4ea9-8362-4a4824a6b43e.png)

**Comment by tgreiser** [comment]
One of my clients has the same issue on Windows 11 Pro. Issue happens in Chrome as well as in electron (chromium). Seems specific to that computer. Reproduceable there, but not on other computers.

**Comment by breezyJake** [comment]
We use an older version of pdf.js to render pdf resume's and we are seeing the same issue on Chromium browsers intermittently. What information would be useful to narrow down this issue?

**Comment by RayHemm** [comment]
Some of our customers are using current DELL XPS 13 notebooks with Iris Graphics. They encounter the same issue with Chromium-based browsers. If you disable the hardware acceleration in Chrome the issue is gone. With Intel UHD we do not encounter any issues. No issues with AMD and NVIDIA.

**Comment by albertbal** [comment]
Same problem here. We couldn't find a way to reproduce it yet. But we verified it affects most of our users on the PDF.js version 2.10.377, and it doesn't affects users on version 2.8.335.

**Comment by Anton-MM** [comment]
Some of our clients see the same thing. It seems to be an issue with the TextLayer. The text there is supposed to be transparent but somehow it is not. If you hide the text layer the problem is gone. We have not been able to reproduce the issue so it is hard for us to debug.

**Comment by Rstyl3** [comment]
I have the same issue and refreshing the page/canvas changes the missing fragments. The workaround I have, is to disable "Accelerated 2D canvas" in Chrome. You can check [Here](https://support.papersapp.com/support/solutions/articles/30000046026-pdf-rendering-issues-in-google-chrome-on-windows-10)

**Comment by bmrinal** [comment]
is there any acknowledgement of issue from the maintainers? We are having the same issue. Any idea when this might be fixed?

**Comment by Snuffleupagus** [comment]
This document looks just fine in Firefox, which is the *primary* development target for the PDF.js library.
Hence it's not clear that it's necessarily an actionable bug *here*, and it may very well be a browser-bug (in Google Chrome).

**Comment by PawelW13i** [comment]
@Snuffleupagus it is a bit strange as it is actually working on PDF.js 2.7.570 and stops working on same browser version but on PDF.js 2.13.216. In our case there are multiple versions of PDF.js between but maybe others observed from what version to what they upgraded when they observed the issue.

**Comment by marco-c** [comment]
It is entirely possible that we started doing something that trips Chrome, especially given what @Rstyl3 mentioned regarding the problem disappearing when disabling hardware acceleration in Chrome.

**Comment by ToxicSmurf** [comment]
> This document looks just fine in Firefox, which is the _primary_ development target for the PDF.js library. Hence it's not clear that it's necessarily an actionable bug _here_, and it may very well be a browser-bug (in Google Chrome).

By primary dev target, do you mean _only_ dev target? The Chrome extension hasn't been updated in three years.

**Comment by jwikman** [comment]
I'm having the same issue on Edge v106.0.1370.42 when having the setting `Use hardware acceleration when available.` enabled. Disabling that setting solves the issue, but then I have no hardware acceleration in Edge... 😕

I'm running on a Dell XPS15 9510.
Edge is using the Intel(R) UHD Graphics GPU when this happens. 

If I [force MS Edge to use my other GPU](https://www.windowscentral.com/how-force-microsoft-edge-use-best-gpu-windows-10-april-2018-update), NVIDIA GeForce RTX 3050 Ti, the PDF looks good. The downside of using this GPU is that Power Consumption increases...

But anyway, I got two workarounds with their own downsides:
- Disable Hardware Acceleration in Edge
- Force Edge to use another GPU (if available)

But I hope that the root cause of this this will be solved.

**Comment by monsterfish** [comment]
Hi, is there any update available to this pdf/browser bug?

**Comment by calixteman** [comment]
As @Snuffleupagus said in https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1154338428, our main focus is Firefox so there are almost no chance we spend some time on this issue.
But, you can either:
 - file a bug on Chrome [bug tracker](https://bugs.chromium.org/p/chromium/issues/list)
 - or if you're sure it's a pdf.js issue or something we can easily workaround, then find someone to work on it and make a pull request.

Considering the comment https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1144783843, it's very likely a Chrome issue.
FYI, I tested this pdf in Chrome and Safari on mac 13.0 and the rendering is ok. I tested on Windows 11, and the rendering is ok in Chrome on hdpi screen but it's far from perfect on a non-hdpi screen.
So really if the issue is because of a mix of Chrome, gpu and screen, as far as I can tell we won't fix this issue here.

**Comment by calixteman** [comment]
Out of curiosity, did you open the pdf in Acrobat ??
Because if you did, you'd have seen the result is worst in Acrobat compared to Chrome.

The main reason is that there is only an image rendered in this pdf, and it has the property `Interpolate` set to `false` (see [8.9.5.3 Image Interpolation](https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#G7.1851981)) .
And few months ago we fixed a bug about that:
https://github.com/mozilla/pdf.js/pull/13991
But in Firefox, image smoothing is enabled when the image is downscaled:
https://searchfox.org/mozilla-central/rev/3c194fa1d6f339036d2ec9516bd310c6ad612859/dom/canvas/CanvasRenderingContext2D.cpp#4933

Anyway, pdf.js is still a free product, some contributors work for it for free and on their spare time. So don't hesitate to help us in using `git bisect` or whatever tool in order to pinpoint a potential culprit and then we can discuss the opportunity to improve (or not) the way to render things.
And if you don't have the answers you want or you aren't happy with our answers, I'm sorry about that, but you can contribute to this project or pay some people to help, instead of just waiting and pinging us...

**Comment by PawelW13i** [comment]
@calixteman - yes I opened it in Acrobat, and the view is better than in Chrome + PDF.js, I usually use FoxIt which is even better on preview.

I know I can contribute and this is not about it, I know that this is free product so I don't expect support more than help from other who know this product better, and what more - your answer was super great and finally brought some light to this topic. 
Now I think if I understand it correctly - the Firefox overrides anyway the image rendered by PDF.js and adds/switches image smoothing. Conclusion is that I can now pass this information to PDF providers to switch the "interpolate" flag and than the problem should is gone.

Thank you much @calixteman for this, now you can even close it as "working as design".

**Comment by calixteman** [comment]
In Acrobat, there is a pref to enable image smoothing which isn't enabled by default (I just discovered it today).

**Comment by joshpotterton-pagesuite** [comment]
Firstly, thanks for all the detail in the responses on this thread, it's been very helpful!

I had a couple of questions in regards to:

#15659 Now I think if I understand it correctly - the Firefox overrides anyway the image rendered by PDF.js and adds/switches image smoothing. Conclusion is that I can now pass this information to PDF providers to switch the "interpolate" flag and than the problem should is gone.

1. Would image smoothing be in reference to imageSmoothingEnabled on the canvas context?
2. When you mention the interpolate flag, wouldn't this just be for image based PDFs? I was a bit confused as the PDF posted in the OP was pretty much all text

Any other information anyone has too would be much appreciated as this is an issue I'm struggling to replicate. Only seems to be users on Dell laptops (not all of them, and not always Iris Graphics). Randomly had one on a Lenovo report the same thing too

**Comment by PawelW13i** [comment]
@joshpotterton-pagesuite from my recent experience - PDF which we use is text based, with "interpolate" flag changed the smoothing is visible as on any zoom in and zoom out the gaps in letters are filled better.
In general I think nowadays this flag in standard should be set to true :) I think most of computers are able to handle documents fast enough with smoothing - but this is not a scope here.

**Comment by albertbal** [comment]
I bought a Dell XPS laptop with an Iris Graphics card to fix this, and I was finally able to reproduce the error consistently.

I think it has nothing to do with image interpolation.

The problem is in the canvas text rendering, and I reproduced it on all pdf.js 3 and 2 versions (3.0.279 - 2.0.943). It happens on all Chromium-based browsers with hardware acceleration enabled (it's the default). 

The problem is on the ctx.fillText calls on canvas.js, and it happens on the first page render only. Re-rendering the page fixes the issue, and adding a delay on each ctx.fillText fixes it too, so it's probably some kind of race condition on the initialization.

I'm still working on a definitive solution, but a workaround is to add { willReadFrequently: true } on all getContext calls both in pdf.js and pdf.worker.js to disable hardware acceleration on the Canvas. I didn't notice any significant performance impact.

**Comment by calixteman** [comment]
As we already said it: it's an issue in Chrome...
I don't really understand why you guys want us to fix it when, really, it isn't our fault.
So please, file a bug on Chrome bug tracker and add a link here in order to be able to follow it.

@albertbal, if you add a `return` at the first line of `showText` then you'll see that the pdf is still rendered: so really what you see on your screen is an image (I'm talking of course about the pdf in https://github.com/mozilla/pdf.js/issues/14641#issue-1161427541).
And if you look in the pdf you'll see some `3 Tr` which mean that the text rendering mode is set to 3 which means that the text is invisible.
But, afaik, hardware acceleration implies that the drawing is done on the gpu, which really should be faster that rendering on the cpu. One problem we have in pdf.js is that we're drawing letters one by one (because we don't want to let the canvas doing the layout of the strings) and possibly it induces a slowdown which causes moving data from the gpu to the cpu and then something is wrong.

In Firefox, `willReadFrequently` has no effect, but in the future it could be plugged in order to be able to disable to hardware acceleration.

**Comment by albertbal** [comment]
I understand, and it's clearly not your fault. I'm not asking you to fix it, I'm trying to do it by myself.
I wasn't able to reproduce it with just a canvas without pdf.js yet. So it's difficult to fill a bug elsewhere.

In any case, this is affecting a lot of users, and I wanted to add some more info here because it's where it can help the most people at the moment.

Thank you for the explanation about the interpolation, I get it now. I was not trying with that PDF. It happens to any PDF with text. The compressed.tracemonkey-pldi-09.pdf for example:

![screenshot](https://codingfocus.com/img/screenshot.jpeg)

Yes, willReadFrequently should slow it down, but it doesn't seem to have so much impact. I know it's not a solution you could add to the library, but it's a quick fix for anyone who needs it.

**Comment by joshpotterton-pagesuite** [comment]
Going off what @albertbal mentioned in re: to `willReadFrequently: true`, if I add this to all the `getContext('2d')`'s in the pdf.js code it seems to be a workaround on v1.9.426 but interestingly not v2.14.305 or v3.0.279. I'll try out some other versions and try to track down why this might be

Not sure why that'd be the case right now, but figured it's worth sharing in case anyone has any extra info

**Comment by icechat** [comment]
Thank you for your attention to this matter, and that it is not a pdf.js issue, and I do see that a chrome bug has been submitted for this at https://bugs.chromium.org/p/chromium/issues/detail?id=1382692

**Comment by hrvojelabtiva** [comment]
@albertbal got it right! I can confirm that using `willReadFrequently: true` in _all_ the `getContext('2d')` calls across the library code fixes the issue by forcing software rendering. I've tested this with the latest 3.x version. Please note that it's important to modify _all_ the calls to `getContext`, since I assume that some rendering is done in the _worker_ and then just copied to the main canvas as an image.

**Comment by whughes98144** [comment]
I was pretty excited about this fix as my work uses PDFJS extensively and we were considering turning it off.  This 'fix' worked ... for many document but strangely not all of them.  Not sure yet how to characterize the differences as I haven't gone through them deeply but there are so many weird PDFs in the world.  So this helps, but isn't a complete fix afaik at this moment.

**Comment by hrvojelabtiva** [comment]
1. For these PDFs that still render incorrectly, does disabling "Accelerated 2D canvas" in chrome://flags help?
2. If by chance the PDFs are suitable to be shared can you attach an example PDF?

**Comment by whughes98144** [comment]
@hrvojelabtiva Yes!  Your first suggestion does work for those PDFs that still show the problem.  However, I need a JS solution as we can't easily ask customers (many very non-technical) to follow this.  Which, I believe, there is not.

**Comment by hrvojelabtiva** [comment]
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext) official docs:

<img width="775" alt="Screenshot 2022-12-02 at 07 56 48" src="https://user-images.githubusercontent.com/9571114/205234079-c4542ebf-00a6-4d61-9f3a-40df4e309df8.png">

<img width="800" alt="Screenshot 2022-12-02 at 07 59 41" src="https://user-images.githubusercontent.com/9571114/205234340-4f61cbb7-ca3d-4c96-a535-54f01710fc75.png">

@whughes98144, since you verified that turning off Accelerated 2D canvas in chrome fixes this problem - there are only two explanations possible:

1. Chrome/Edge fails to respect the flag in full (MDN states if has full support from version 99)
2. You have failed to to modify _all_ the calls to `getContext` in the pdf.js source

**Comment by whughes98144** [comment]
GAH!  @hrvojelabtiva YOU ARE CORRECT!! Intellij wasn't handling the minified version of pdfjs well and only showed me one of the getContext calls.  THANK you for replying as it made me triple check and find the other calls.  Once I added the willReadFrequently everywhere, I saw no PDFs that still showed the problem. I don't love this mitigation but it's better than not having it

**Comment by callabr1** [comment]
Hi all! I commented in [the other thread](https://github.com/wojtekmaj/react-pdf/issues/1010) as well, but figured I'd pasta here too:

I am a QA tester for a webapp that uses react-pdf/pdf.js to render PDFs and we had a few customer reports about this issue with Chrome/Edge as well. I was originally unable to reproduce the issue until the company sent me a specific laptop...

From all the testing and investigation I've done, the issue seems to be tied to having the following four things:
1. App rendering PDFs using react-pdf/pdf.js
2. Chromium browser
3. **Intel Iris Xe Graphics** GPU (or similar integrated laptop GPU)
4. Specific PDF fonts (as the issue is not reproducible with all PDFs)

I have two different Windows ThinkPad laptops; one with a nVidia GPU and the other with the Intel Iris. I can only reproduce the issue on the Iris book, not the nVidia one. This goes in line with our clients' system specs, as well. 
There are other integrated GPUs that will also see the issue but the Iris seems to be the most common. I could provide some other affected cards if needed, though.

If anyone needs me to test potential fixes on my affected device, I am more than happy to as long as it does not impede on any enterprise security protocols; the machine I have for testing is from work. Let me know, I hope narrowing it down to certain GPUs helps!

**Comment by hrvojelabtiva** [comment]
@callabr1 since I do believe this is a purely a **Chromium** bug (not pdf.js), what would be most useful is to create a minimal example of this _without_ using pdf.js and submit that to the Chromium team along with the hardware details. There is already an open [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1382692) for this. Here's a naive [attempt](https://jsfiddle.net/cxrznbso/1/), but one ingredient that is surely missing is the "problematic" font.

**Comment by hrvojelabtiva** [comment]
@callabr1 - thanks for trying, as I said, my example was very naive and simple, and there's probably more to this - specifically isolating how pdf.js renders these fonts and recreating a minimal example off of that. But this is more than I have time for at the moment.

**Comment by calixteman** [comment]
You can try to play with: https://github.com/Rob--W/canvas-interceptor
in plugging it in the various places where we create a canvas and then you should be able create a minimal piece of code.

**Comment by 1Jesper1** [comment]
> @callabr1 since I do believe this is a purely a **Chromium** bug (not pdf.js), what would be most useful is to create a minimal example of this _without_ using pdf.js and submit that to the Chromium team along with the hardware details. There is already an open [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1382692) for this. Here's a naive [attempt](https://jsfiddle.net/cxrznbso/1/), but one ingredient that is surely missing is the "problematic" font.

Try this: https://jsfiddle.net/rdgfx6zh/1/ Using roboto font

**Comment by callabr1** [comment]
Hello @1Jesper1 thanks for the suggestion
> Try this: https://jsfiddle.net/3kt6v82s/1/ Using roboto font

I tried, no dice - the text looks fine on the affected device. I tried changing the sentences displayed, the font size, and all variants of Roboto (bold, italic, MT). I'll keep playing around on jsfiddle but so far been unable to repro it there.

**Comment by stenvala** [comment]
> Thank you for your attention to this matter, and that it is not a pdf.js issue, and I do see that a chrome bug has been submitted for this at https://bugs.chromium.org/p/chromium/issues/detail?id=1382692

What makes you think that the linked chromium bug is associated to this? Looks like that it is related to sometimes hiding text completely because text rendering bounds go to 0. The issue reported here seems to be more related to not rendering well pdf files where the content is raster image.

**Comment by 1Jesper1** [comment]
> > Thank you for your attention to this matter, and that it is not a pdf.js issue, and I do see that a chrome bug has been submitted for this at https://bugs.chromium.org/p/chromium/issues/detail?id=1382692
> 
> What makes you think that the linked chromium bug is associated to this? Looks like that it is related to sometimes hiding text completely because text rendering bounds go to 0. The issue reported here seems to be more related to not rendering well pdf files where the content is raster image.

Looks like a different problem indeed, maybe we should report a new bug to Chrome?

**Comment by callabr1** [comment]
> > > Thank you for your attention to this matter, and that it is not a pdf.js issue, and I do see that a chrome bug has been submitted for this at https://bugs.chromium.org/p/chromium/issues/detail?id=1382692
> > 
> > 
> > What makes you think that the linked chromium bug is associated to this? Looks like that it is related to sometimes hiding text completely because text rendering bounds go to 0. The issue reported here seems to be more related to not rendering well pdf files where the content is raster image.
> 
> Looks like a different problem indeed, maybe we should report a new bug to Chrome?

I was about to enter a bug in Chromium as I don't see anything *exactly* like it, only similar (like the aforementioned zoom bug). However I realize when submitting there it'll automatically log my PC specs, and I left the affected device at home today 🙃 I will log a new issue in 4-5 hours, when I get home from office.

@stenvala I'll link the new Chromium issue tonight after I enter it, but for now it seems the most information and tracking can be done in related issue https://github.com/wojtekmaj/react-pdf/issues/1010 which is still open and has an attached MR which *somewhat* fixes the issue (some text was fixed, but PDFs with images seem to render badly still).

**Comment by 1Jesper1** [comment]
@callabr1 Did you file a new Chromium issue?

**Comment by callabr1** [comment]
> @callabr1 Did you file a new Chromium issue?

Yes I did, sorry I didn't enter it until I was back from holiday but it's here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1404710

I'm trying to get a screen cast for them now, but my work disabled all the recording options on my device (they are locked to admin rights) - trying to get that sorted out to give a full video now :)

**Comment by martin-kl** [comment]
A new [Chromium commit](https://chromium.googlesource.com/chromium/src/+/4b66688abb9c3bf5ac1a0fafe7f9ebad52624a99) from today seems to fix the issue, at least on my XPS with an Iris Xe Graphics that has the same problems with the latest stable Chrome version whereas the latest Canary build works (with hardware acceleration enabled! ).

**Comment by jransonhayes** [comment]
I still have the glitches on the canary version that introduces that commit (111.0.5530.0) too.

[This suggests it is a different issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1404710#c11)

**Comment by devalberg** [comment]
Maybe someone out there will find this useful...

I've discovered a naive "workaround" until Chrome fixes the issue, in our PDF viewer code I called the `PDFPageProxy.render` multiple times which seems to make the document look correct.

```tsx
// 5 is arbitrary, 2 works but 5 is just to be sure.
// The higher the number the slower the render (page stays white longer), 5 isn't noticable.
for (let i = 0; i < 5; i++) {
        await page.proxy.render({ canvasContext: ctx, viewport }).promise;
 }
```

I came to this conclusion because I noticed when zooming in and out the document somehow fixes itself. Tested triggering auto zoom-in-out but that didn't consistently work. Then I tried to do that multiple times but no luck either - Finally tried this and seems to work out fine.

**Comment by achanizbekov** [comment]
> 
Thank you. It worked in my case!!

**Comment by pluengom** [comment]
> > 
> 
> @devalberg Thank you. It worked in my case!!

I'm not sure where you put that code, can you help me please? 

Thanks in advance.-

**Comment by achanizbekov** [comment]
> > > 
> > 
> > 
> > @devalberg Thank you. It worked in my case!!
> 
> I'm not sure where you put that code, can you help me please?
> 
> Thanks in advance.-

@pluengom It's easy. You don't have to put the same code, in my case it didn't work(_'await' expressions are only allowed within async functions and at the top levels of modules._). But as @devalberg said, you have to call render of pdf page multiple times. In my case it looks so:
Before fix:
`var renderTask = page.render(renderContext);
renderTask.promise.then(function () {
...
});`

After fix:
`var renderTask = page.render(renderContext);
renderTask.promise.then(function () {
    renderTask = page.render(renderContext);
    renderTask.promise.then(function () {
        ...
    });
});`

**Comment by pluengom** [comment]
> > > > 
> > > 
> > > 
> > > @devalberg Thank you. It worked in my case!!
> > 
> > 
> > I'm not sure where you put that code, can you help me please?
> > Thanks in advance.-
> 
> @pluengom It's easy. You don't have to put the same code, in my case it didn't work(_'await' expressions are only allowed within async functions and at the top levels of modules._). But as @devalberg said, you have to call render of pdf page multiple times. In my case it looks so: Before fix: `var renderTask = page.render(renderContext);` `renderTask.promise.then(function () {` `...` `});`
> 
> After fix: `var renderTask = page.render(renderContext);` `renderTask.promise.then(function () {` ` renderTask = page.render(renderContext);` ` renderTask.promise.then(function () {` ` ...` ` });` `});`

Many thanks for the answer.
It worked perfectly.

**Comment by maybephilipp** [comment]
I don't know exactly how, but `PDFPageView` view class does work like a charm and fixes text distortion completely. I've adapted it instead of my previous solution and now it looks perfect!

Solution with rerendering a page N times doesn't solve the problem completely. After few iterations page looks better, but still distorted in many places.

**Comment by suryaprythvi** [comment]
@ma

> I don't know exactly how, but `PDFPageView` view class does work like a charm and fixes text distortion completely. I've adapted it instead of my previous solution and now it looks perfect!
> 
> Solution with rerendering a page N times doesn't solve the problem completely. After few iterations page looks better, but still distorted in many places.
> 
> Took an example from there: https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js

@maybephilipp 
Can you provide more details on how you fixed the text distortion? I am using 2.16.105 version of pdf.js.
Thanks in advance

**Comment by maybephilipp** [comment]
> Can you provide more details on how you fixed the text distortion? I am using 2.16.105 version of pdf.js. I am facing the rendering issue with chromium browsers on certain windows machines only.
> Thanks in advance

@suryaprythvi Here is a adapted version of our React code. Sorry if some syntax or vars will not work. General idea of implementation is present.

```javascript
import * as pdfJS from 'pdfjs-dist'
import * as pdfJSWeb from 'pdfjs-dist/web/pdf_viewer'
import 'pdfjs-dist/web/pdf_viewer.css'

const eventBus = new pdfJSWeb.EventBus();

const loadedDoc = await pdfJS.getDocument({
  url: activePdf.url,
}).promise

const page = await doc.getPage(pageNum)

const origViewport = page.getViewport({ scale: 1 })
const scale = wrapperSize.width / origViewport.width

const viewport = page.getViewport({ scale })

const pageView = new pdfJSWeb.PDFPageView({
  container: canvas,
  id: pageNum,
  scale: 1,
  defaultViewport: viewport,
  eventBus,
})

pageView.setPdfPage(page)

pageView.draw()
```

**Comment by wmerobertson** [comment]
Hi @Snuffleupagus and @calixteman,

I believe there are two separate bugs being discussed within this ticket. In the PDF posted initially by @PawelW13i the text is blurry and does not look smooth. The PDF in this [comment](https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1315265210) has chunks of letters missing and is unreadable in some places.

I have a PDF where I can reproduce the initial issue reported. The issue with chunks of letters missing I cannot reproduce on my ARM Mac using Chrome. I believe I cannot reproduce this because I do not have one of the specified graphics cards mentioned on the chromium [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1404710).

I am working on a fix for the initial issue. I am able to fix the blurriness by forcing `img/imgData.interpolate` to be `true` on the following two lines in canvas.js

- https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L1344
- https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L2994

I can achieve this by adding an `enableInterpolation` option to `defaultOption` and accessing that option in canvas.js.

Does this sound right to you all? Would you be open to a PR that adds `enableInterpolation` as an option that consumers could toggle?

Thanks!

**Comment by Snuffleupagus** [comment]
> Would you be open to a PR that adds `enableInterpolation` as an option that consumers could toggle?

Sorry, but I'm not at all excited about that unfortunately. Please keep in mind that all options have a maintenance/support burden, and none of this applies to Firefox (which is *primary* development target for this library).

Note that this is a bug (or possibly multiple bugs) specific to a particular combination of one browser (i.e. Google Chrome), certain graphics card, and hardware acceleration being enabled; hence it doesn't seem entirely reasonable that we should have to "work-around" that here.
