### ISSUE TITLE
Document is blurry

### ISSUE THREAD

**Issue by mikecoulhs** [mozilla/pdf.js#14724]
Attach (recommended) or Link to PDF file here:
[Infographic_EAP_EN_v2 (1).pdf](https://github.com/mozilla/pdf.js/files/8365628/Infographic_EAP_EN_v2.1.pdf)

Configuration:
- Web browser and its version:
Chrome Version 99.0.4844.51 (Official Build) (x86_64)
- Operating system and its version:
macOS Catalina 10.15.7
- PDF.js version:
Repros with version at [PDF.js Demo Viewer](https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension:
No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the file 
This is how the document appears in Adobe Acrobat Reader:
![image](https://user-images.githubusercontent.com/22301903/160471064-e4372724-e834-464b-8a32-f9ebd43eb3a2.png)

This is how it appears in the viewer.  (Please view in full size) Note the lack of crispness of the text in particular.
![image](https://user-images.githubusercontent.com/22301903/160471285-829fea1b-45dd-471b-8908-4bc4049f7a31.png)

Thank you!

**Comment by luisberth** [comment]
It seems like pdf.js is having issues with the newest version of Chrome.
In my case, when rendering a pdf in a canvas, the text is rendered in a weird way, like choped.

**Comment by mikecoulhs** [comment]
HI @luisberth , I just tried it in firefox and it appears the same.  The text is similarly blurry and the document is clipped halfway down.

**Comment by SamyCookie** [comment]
Hello, I also confirm the issue on a Linux Debian Bookworm 64bits with Firefox 98 and the embedded PDF.js reader.

**Comment by calixteman** [comment]
I think the text blurriness is due to:
https://github.com/mozilla/pdf.js/blob/0dd6bc9a85c29dd36805d120ab0ad2e42b1a6386/src/display/canvas.js#L2667
where there is a `scaleY !== 1` and very likely it's the same cause for the images.

**Comment by margaux0** [comment]
We are having the same issue. Text in high quality images in the pdf is not rendered properly. We have tested the pdf in the web viewer (https://mozilla.github.io/pdf.js/web/viewer.html) to check if we were rendering incorrectly, but have found the same behaviour occurs there.

**Comment by mikecoulhs** [comment]
Hi [calixteman](https://github.com/calixteman)! I was wondering (hoping?) if there was any progress on this?  We're seeing it on a fair number of documents.  Interestingly, it seems like this might be a regression - we have a very old version of pdf.js (1.10.129) that doesn't exhibit the blurriness (at least for one document I've looked at)  Thanks!

**Comment by mikeweilgart** [comment]
I just noticed this stems from Firefox.  I've noticed now on a few financial websites that when I attempt to view OR PRINT a PDF directly from Firefox, the result is blurry and unusable.  Instead I have to download the PDF and then print it from Acrobat Reader to get a crisp printout.

**Comment by marco-c** [comment]
> I just noticed this stems from Firefox. I've noticed now on a few financial websites that when I attempt to view OR PRINT a PDF directly from Firefox, the result is blurry and unusable. Instead I have to download the PDF and then print it from Acrobat Reader to get a crisp printout.

This is a different problem, what you're seeing is https://bugzilla.mozilla.org/show_bug.cgi?id=1274502 (https://bugzilla.mozilla.org/show_bug.cgi?id=1774631 or https://bugzilla.mozilla.org/show_bug.cgi?id=1777209), which are fixed in Firefox 104.

> I also found these other bug reports which seem to be about the same problem:
> 
> #14147
> https://bugzilla.mozilla.org/show_bug.cgi?id=1506953

Yes, this is a duplicate of #14147.

**Comment by mikecoulhs** [comment]
@marco-c I'm a little confused - as reported, this ticket repros in Google Chrome.

**Comment by marco-c** [comment]
It also reproduces in Firefox, the underlying bug is the same.

**Comment by nwang-highspot** [comment]
> I think the text blurriness is due to:
> 
> https://github.com/mozilla/pdf.js/blob/0dd6bc9a85c29dd36805d120ab0ad2e42b1a6386/src/display/canvas.js#L2667
> 
> 
> where there is a `scaleY !== 1` and very likely it's the same cause for the images.

Hi @calixteman How can we fix the problem, seems I can still reproduce the issue.

**Comment by marco-c** [comment]
This issue is not closed because it was fixed, it was closed as a duplicate of #14147.

**Comment by calixteman** [comment]
In order to handle correctly transparency, we use some intermediate canvas and sometimes they can be too big.
So in order to prevent some allocation issues, the group is drawn on a smaller canvas and then resize thanks to a scale transformation:
https://github.com/mozilla/pdf.js/blob/de7d1d2167ad55bc215c98e43d4e0dec25db9b60/src/display/canvas.js#L2885
In the pdf attached to this issue, the bounding box used to compute the canvas dimensions is `[ 0, 0, 5950, 50210 ]` and the height here is a way too big.

**Comment by nwang-highspot** [comment]
> 

@calixteman So what is the recommended size(height) for the canvas dimensions?

**Comment by wmerobertson** [comment]
This looks to be a duplicate of #14982. It is fixed by disabling this block.

[pdf.js/src/display/canvas.js](https://github.com/mozilla/pdf.js/blob/987062c302c01bab72645e28a1ffa3fd457e1eb6/src/display/canvas.js#L2665-L2672)
