### ISSUE TITLE
[Bug]: Print is broken with prebuilt on Firefox

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/pdf.js#19988]
### Attach (recommended) or Link to PDF file

.

### Web browser and its version

Firefox 139

### Operating system and its version

Windows 11

### PDF.js version

5.3.31

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Host the latest version of the prebuild on a personal server without any modifications.
3. Open the viewer page with the default PDF or upload any pdf
4. Try to print

### What is the expected behavior?

The print window open this the PDF preview

### What went wrong?

A blank page is previewed, except for a broken image in the center
If you press Shift + reload button, the print preview works.
But if I refresh again without the shift, the printout is broken again.

No error in console.

This works correctly with Chrome.

The demo of the https://mozilla.github.io/pdf.js/web/viewer.html site works correctly.

### Additional context

![Image](https://github.com/user-attachments/assets/1a559ab6-e9cc-4566-9d6f-ab5b718091d8)

What could be causing this?

**Comment by n-goncalves** [comment]
Same issue here, down to the details described of it working if you force reload. 

I'm using PDFjs version 5.4.149 and trying on Firefox 143.0 for Linux.

**Comment by jdeepwell** [comment]
+1 on this, 143.0.1 (aarch64) on macOS 15.5 (24F74) and Zen 1.16.1b (Firefox 143.0.1) (aarch64) on macOS 15.5 (24F74)

The forced reload also "fixes" it.
Also no errors in the console - neither in page nor directly in worker console.

**Comment by calixteman** [comment]
I just tried on Windows 11 with Firefox 139 and the last release:
https://github.com/mozilla/pdf.js/releases#:~:text=Assets
I uncompressed it and serve it with a local server, opened a pdf and printed it: everything was working perfectly.
Maybe you can try to open the browser console and if there's an error message:

<img width="3279" height="1214" alt="Image" src="https://github.com/user-attachments/assets/129abf37-a260-4549-bfb4-81436d236492" />

**Comment by jdeepwell** [comment]
Hey @calixteman  - thx for the reply!
As said the console unfortunately is silent - even with "debug" output enabled.

All I see there is
```
PDF 433eb25a1f930385f1062d45b0a6e86c [1.4 Skia/PDF m127 / Chromium] (PDF.js: 5.4.149 [9e2e9e209])
```

I'm running some tests currently and there is a slight possibility that our service worker might be connected to the issue. When I stop it, I can print - when it runs, I cannot. Although that does not explain why printing also works after a forced reload, even when the SW is running...

@n-goncalves  and @SuperPat45 : Do you also have service workers in your project in which this issue shows?

**Comment by SuperPat45** [comment]
I have a service worker for the notification push API, but It has no fetch event listener registered

**Comment by jdeepwell** [comment]
Our service worker also does mainly push notifications (it also keeps a websocket connection for other stuff). We also have no fetch event listener.

And yet:
- I open the page with the PDF viewer
- I open the print preview -> empty pages with broken image icon
- I reload (not force reload!!) the PDF viewer page
- I open the print preview -> empty pages with broken image icon
- I terminate/unregister the service worker via `about:debugging#/runtime/this-firefox`
- I reload (not force reload!!) the PDF viewer page
- I open the print preview -> works!
- I load a different page that re-registers the service worker - service worker now running again
- In the PDF viewer page - **without any reloading** open the print preview again -> empty pages with broken image icon
- I **force** reload the PDF viewer page and open the print preview again (service worker still running) -> it works.

So: Whether the service worker is running or not clearly has *some* influence. But even if it is running, a force reload of the PDF viewer page nevertheless makes the preview work again.

I will now extract just the components of our site needed to reproduce the issue into a test site and then will try to strip down the service worker piece by piece to find out what in it has this bad influence on the PDF viewer. But maybe it is the mere fact that there _is_ a service worker...

**Comment by jdeepwell** [comment]
OK, so the connection to the service worker is quite definitive.

I made a test-site that is as reduced as possible:

1. The `web` and `build` folders of PDF.js (two copies, one within the scope of the service worker, one outside)
2. A pdf file
3. A service worker
4. A page that loads the service worker and communicates with it via messageChannel

## Service Worker
This is the bare-bones service worker:
```JavaScript
console.log('Service Worker: Script loaded');

// Service worker installation
self.addEventListener('install', (event) => {
  console.log('Service Worker: Installed');
});

// Service worker activation
self.addEventListener('activate', (event) => {
  console.log('Service Worker: Activated');
});

// Listen for messages from the page
self.addEventListener('message', (event) => {
  console.log('Service Worker: Received message from page:', event.data);
  
  // Send a response back to the page
  event.ports[0].postMessage({
    response: 'Hello from Service Worker!',
    received: event.data
  });
});
```

The service worker is loaded via `navigator.serviceWorker.register('/sw.js', { scope: '/sw_scope' })` – so it's scope is the sub-folder `/sw_scope`

## Directory structure 
```
/
/test.pdf
/www
/build
/sw.js
/sw_scope
/sw_scope/www
/sw_scope/build
/sw_scope/load_sw.html
```


## Findings

As soon as the PDF viewer page is controlled by a service worker (even one without a "fetch" handler!), the issue shows. Force-reloading the page suppresses the issue once, but loading the page again (via link or "normal" reload) makes the issue re-appear.

On a PDF viewer page that is outside of the scope of the service worker the issue does **not** show. Whether the service worker is running/registered does **not** matter then.

So if I load `https://testserver....com/web/viewer.html?file=/test.pdf` the print preview always works - no matter whether the service worker is running/registered. No force-reload needed.

But if I load `https://testserver....com/sw_scope/web/viewer.html?file=/test.pdf` (after registering/loading the service worker!) the print preview shows the empty pages again. If I then terminate the service worker it will work permanently (even when I load the viewer page again), if I just force-reload the viewer page, it will work until I load the viewer page again.

**Comment by jdeepwell** [comment]
For completeness I am attaching the test server's htdocs...

[www.zip](https://github.com/user-attachments/files/22646867/www.zip)

**Comment by jdeepwell** [comment]
@calixteman Is there any more information I can provide so that you can reproduce the issue?

**Comment by SuperPat45** [comment]
I confirm that it works fine when I remove the service worker.
It's strange, why would the service worker interfere with printing?

**Comment by jdeepwell** [comment]
It also works fine when pdf.js lib and the viewer are served from a path that the SW is not registered to. So just the fact that a SW is present, is not the issue. But if the SW is responsible for the assets the viewer needs (it is registered to that path), then the bug bites.

I also implemented a basic fetch event listener in my test SW - just to see when it is used and for what.

When one does a force-reload on the page, the browser will of course _not_ use the SW (as force-reload does mean _do not use cache_) and then the print preview works fine again - once. When you access the viewer page again (via link or normal reload), it fails again.

To be clear: It's not relevant whether the _PDF file_ is located under a path that the SW is registered to. The bug bites when the _the pdf.js lib and the viewer_ is coming from a path the SW is registered to!

In my test setup I have the SW set up so it is registered to the scope `/sw_scope` and I have the pdf.js lib, the viewer files and the PDF file duplicated, _outside_ of that folder and _inside_ of it.

When I access the viewer and lib from outside, everything works fine (even with the SW running and registered) - no matter if I load the PDF from outside or inside the `/sw_scope` folder.

But when I access the viewer and lib from inside the `/sw_scope` folder, the bug bites (again, no matter whether the PDF file comes from inside or outside the scope).

The fact that in the error case pdf.js will generate a broken image icon for each page in the print preview _and_ in the generated PDF seems to indicate that it was not able to load the PDF file in this situation (even though it displayed the PDF in the viewer just fine) - but it does not generate _any_ error message in the browser console.

BTW: When using Firefox's built-in pdf.js lib everything works fine – even with the SW. That is why as a workaround for now we use the built-in version when the client uses Firefox. That of course is not a solution, as we cannot do the viewer customizations we need with the built in one. (and no, for my tests I did _not_ use our customized viewer - I used the original one from the build!)

**Comment by Fl0Cri** [comment]
I also encountered this bug while trying to update PDF.js from 3.10.111 to 5.5.207. I have a Service Worker doing essentially nothing (only present so browsers detect an installable PWA).

Removing the Service Worker does resolve the issue, as well as rolling back to 3.10.

I've searched through the changes in `pdf_print_service.js` between these versions and it seems this issue is caused by https://github.com/mozilla/pdf.js/commit/6a1b1ae6a42fcc421d513852b9164be04097b96b.

I tried commenting out the `URL.revokeObjectURL()` call. It resolves the issue, but probably reintroduces the memory leak this commit was fixing...

As I interpret it, PDF.js's printing works as follows:
1. Render all pages as images in a div with id `#printContainer`
2. Revoke the urls to these images immediately once they are loaded
3. Call the browser's window.print() function. Some CSS with `@media print` takes care of showing only the `#printContainer` during the print

Maybe Firefox is doing some isolation with URL objects of Blobs created by scripts served by a Service Worker, and the fact that PDF.js revokes them immediately is conflicting with this?

I managed to work around the issue without modifying PDF.js by intercepting and copying the `#printContainer` and "steal" the image urls so they don't get revoked. Here's a minimal example (it seems to work, but I am not confident it won't break in the future...)

The following code runs inside `PDFViewerApplication.initializedPromise.then(...)`. It is also needed to copy the CSS of `#printContainer` so it applies to `#printContainerCopy` instead.
```js
// A dummy image we will use to swap the rendered pages with
const dummyImage = new Blob(['<svg xmlns="http://www.w3.org/2000/svg"></svg>'], {type: 'image/svg+xml'});

//
// Still perform some cleanup, trying to avoid leaking memory
//
const stolenObjectUrls = new Set();

function cleanupStolenObjectUrls() {
    stolenObjectUrls.forEach((url) => URL.revokeObjectURL(url));
    stolenObjectUrls.clear();
}

PDFViewerApplication.eventBus.on("beforeprint", cleanupStolenObjectUrls);
document.addEventListener('beforeunload', cleanupStolenObjectUrls);

//
// Keep the clone synchronized with the original printContainer
//
const observer = new MutationObserver(syncSavedPrintVersion);
observer.observe(document.getElementById("printContainer"), {
    childList: true,
    subtree: true,
    attributes: true
});

function syncSavedPrintVersion() {
    if (!PDFViewerApplication.printService) {
        return;
    }

    // Steal rendered pages from the printContainer
    const baseContainer = document.getElementById("printContainer");
    baseContainer.querySelectorAll("img").forEach(function(img) {
        if (img.src && !img.getAttribute('data-original-src')) {
            stolenObjectUrls.add(img.src);
            img.setAttribute('data-original-src', img.src); // Gimme this blob
            img.src = URL.createObjectURL(dummyImage); // Revoke that instead
        }
    });

    $('#printContainerCopy').remove(); // Remove previous clone if there is one, using jQuery for a one-liner

    // Clone the printContainer and restore the rendered pages
    const copyContainer = baseContainer.cloneNode(true);
    copyContainer.querySelectorAll("img").forEach(function(img) {
        if (img.getAttribute('data-original-src')) {
            img.src = img.getAttribute('data-original-src');
        }
    });
    copyContainer.id = "printContainerCopy";
    baseContainer.parentElement.appendChild(copyContainer);
}
```

**Comment by jdeepwell** [comment]
It turned out that at least with PDF.js 5.4.296 the issues only shows in Firefox. So for us the workaround was to simply do not use PDF.js in Firefox and let Firefox handle the PDF (which in turn uses its own PDF.js anyway)

**Comment by jdeepwell** [comment]
No - I was not back then when I worked on that issue - only with Firefox. I just again tried with Chrome/Brave - no issue.
Right now I cannot check whether the current version of Firefox still has this issue because I cannot remove the "not for Firefox" filter...

**Comment by Mer0me** [comment]
With Nextcloud 34.0.3 and Firefox 152.0.4 and earlier, the bug still persist with the same exact symptoms. Is it normal ?
pdfjsVersion = "4.10.38"

**Comment by sylvestre** [comment]
@Mer0me please open a new bug
also, pdfjs in the tree is 6.3.335
4.10.38 has been released Tue Dec 31 16:26:13 2024
