### ISSUE TITLE
Automatic page orientation (portrait/landscape)

### ISSUE THREAD

**Issue by agabrielluz** [mozilla/pdf.js#6696]
I'd be better if we had automatic page orientation such as one used on popular apps like Adobe Reader. Do it, please. If not, we have to change page orientation every time. Imagine a book with mixed orientation. That's no good. Thank you for your hard work.

**Comment by agabrielluz** [comment]
Sorry. I don't think I made myself clear. Automatic page orientais should work for PDF files with situation where your app if set up to print as portrait and your PDF is in landscape. The automatic orientation feature would automatically set it as landscape. Foxit Reader has that, too.

**Comment by xlc** [comment]
#6103 should fix this

**Comment by timvandermeij** [comment]
This feature is now implemented and can be enabled by setting the `enablePrintAutoRotate` viewer preference to `true`.

/cc @2Owy

**Comment by 2Owy** [comment]
Thanks Tim,
But this option will be available in Firefox to ? or only in PDFJS library ?

**Comment by timvandermeij** [comment]
The option will be available in both. For the Firefox version, the preference can be set using `about:config` when a new version is released with this patch.

**Comment by JRC18** [comment]
I was wondering if we knew when this might go into production, or if it did and isn't working for me.  Sorry been waiting for this feature for about 2 years and if it is in I still can't get it to work.  Firefox 57 (Quantum).

**Comment by timvandermeij** [comment]
I have it in Firefox 57 in `about:config` under the `pdfjs.enablePrintAutoRotate` key. By default is it `false`, but you can toggle it to `true` there.

**Comment by JRC18** [comment]
Yea, I have that as well but it doesn't seem to do anything.  I'll check more on my side maybe the pdf files are missing an attribute that is needed.

**Comment by gabriellluz** [comment]
Thanks. It works great!

**Comment by JRC18** [comment]
So I unfortunately still have issues with this not working.  I have tried resetting my profile, turning the setting back off then on again and whatever else I could think of to get it to accept the setting.  I went out and randomly found 2 pdf files on the internet to test with [This]( http://www.co.dutchess.ny.us/CountyGov/Departments/StopDWI/DontBlowIt.pdf) and [This](http://www.dutchessny.gov/CountyGov/Departments/PublicWorks/pcpfs.pdf). Using those same files with Chrome and Adobe Reader it does the autorotate fine.  Printing in Firefox page one from them prints both as portrait, the first one should be landscape.  Any help would be appreciated, this is the one thing I am having issues with for my company users and I would really prefer not to move from Firefox.
![image](https://user-images.githubusercontent.com/33882843/34169499-d3e1ed9e-e4a4-11e7-845d-600d34ddd8a8.png)

**Comment by timvandermeij** [comment]
@JRC18 Thank you for reporting this. I have opened a new issue (#9297) to track the problem that you describe because continuing on a closed issue makes it hard to track the current state of the problem.

**Comment by JRC18** [comment]
Thanks Tim, sorry I wasn't sure how to post it.

**Comment by sundeepnaga** [comment]
Is this issue is fixed

**Comment by ilium007** [comment]
Still an issue. Is it ever going to be fixed?

**Comment by JamieKitson** [comment]
Can confirm this works (type `about:config` in the address bar, search for `enablePrintAutoRotate` and set to `true`). But why on earth isn't this enabled by default? It's been driving me nuts!

**Comment by ilium007** [comment]
This was the first thing I tried - didn't work

**Comment by ilium007** [comment]
68.7.0esr does not have enablePrintAutoRotate, only has pdfjs.enablePrintAutoRotate which does not fix the issue when enabled.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/732766/83635176-1e252280-a5e7-11ea-8cfa-ad4d82808b5f.png">

**Comment by ilium007** [comment]
On OSX 76.0 I do see the two options

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/732766/83635370-752af780-a5e7-11ea-9c20-ea98e7bc2095.png">

**Comment by JamieKitson** [comment]
@ilium007 `pdfjs.enablePrintAutoRotate` is what I set to true and worked for me.

**Comment by LeoBoudet** [comment]
Tried the 'about:config' soluce on debian Buster, Firefox 68.9. It doesn't work.
