### ISSUE TITLE
images in one specific PDF file display all black

### ISSUE THREAD

**Issue by lmamane** [mozilla/pdf.js#7309]
Link to PDF file (or attach file here):
https://support.cessna.com/custsupt/contacts/pubs/ourpdf.pdf?as_id=37309
Configuration:
- Web browser and its version: iceweasel (Debian rebranded Firefox) 38.7.1
- Operating system and its version: Debian GNU/Linux 8.4
- PDF.js version: the one that is built-in in iceweasel
- Is an extension: no, built-in

Steps to reproduce the problem:
1. open PDF in iceweasel
2. go to page 6 or 7 of PDF (marked 4 and 5 in the actual text)

What is the expected behavior? (add screenshot)

technical monochrome drawings shown
![2016-05-10-112145_1172x750_scrot](https://cloud.githubusercontent.com/assets/7558692/15141683/8cac997e-16a1-11e6-8e6f-28004c9639b1.png)

What went wrong? (add screenshot)

drawing is a big all-black rectangle
![2016-05-10-112343_1253x830_scrot](https://cloud.githubusercontent.com/assets/7558692/15141716/ae4d68f6-16a1-11e6-82aa-d431129fc97a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a

**Comment by SamyCookie** [comment]
Same issue with web viewer and Firefox 46.0.1 on same OS.
But I cannot reproduce the bug with web viewer and Firefox 46.0 on Debian Stretch (testing).
So it seems to be distribution specific.

**Comment by timvandermeij** [comment]
Closing as duplicate of #7024.

**Comment by yurydelendik** [comment]
Fixed in FF46, see https://bugzilla.mozilla.org/show_bug.cgi?id=976322

**Comment by timvandermeij** [comment]
Awesome, that explains why I cannot reproduce it anymore!

**Comment by SamyCookie** [comment]
Sorry but I can reproduce this issue even with last Firefox version.

![issue7309](https://cloud.githubusercontent.com/assets/2362591/15177243/64dd8588-176f-11e6-8c12-6418d0750cd3.png)

However, on another machine, with same configuration, this bug does not exist. So I believe that is related to graphics.

**Comment by SamyCookie** [comment]
Oh, strange, this bug is back on the previously working machine...
I upgraded the Firefox package from 
http://snapshot.debian.org/package/firefox/46.0-1/
to
http://snapshot.debian.org/package/firefox/46.0.1-1/

**Comment by SamyCookie** [comment]
One of the possible reason is that the gtk backend version used go back from gtk3 to gtk2 (temporary for regression reason on Debian distribution). So I believe that the fix of this issue is directly related to the gtk3 backend used by Firefox 46 (default). I think there is no need to reopen because gtk2 backend will be deprecated at the end.
I'll confirm all of this when Firefox package will use gtk3 version.
