### ISSUE TITLE
ENOENT: no such file or directory, lstat with # encoded in filename

### ISSUE THREAD

**Issue by njakob** [mozilla/pdf.js#8987]
#8928 actually resolved the issue #8907 I open couple days ago. However, when filenames contain an encoded `#` character (`%23`), current decoding process do not handled it.

Configuration:

* Web browser and its version:
  Electron 1.7.8
* Operating system and its version:
   Fedora 25
* PDF.js version:
  1.9.617

Steps to reproduce the problem:
1. Open a locale file with an `#` encoded character `file:///home/njakob/Foo%20Bar/document%23.pdf`

What went wrong?
* The error `ENOENT: no such file or directory, lstat` is raised.

Issue is related to the [`decodeURI`](https://github.com/mozilla/pdf.js/blob/e4c09c7cba9cb21db447e1e8d00051e97b40f7d8/src/display/node_stream.js#L363) usage which ignore decoding of `%23`.

Solution should also cover cases were the `#` is inside the path such as `file:///home/njakob/Foo%23/document.pdf`.

**Comment by mukulmishra18** [comment]
I think we need to use `decodeURIComponent` instead of `decodeURI` because _decodeURI_ may ignores decoding special characters.

**Comment by shikhar-scs** [comment]
If this issue is still up, may I work on it please?

**Comment by mukulmishra18** [comment]
@shikhar-scs it is yours!

**Comment by shikhar-scs** [comment]
@mukulmishra18 as you have previously worked with `pdf.js`, so I guess you are sure that ` use decodeURIComponent instead of decodeURI` will make the required changes. Correct ? do we need to do something more than this ?

**Comment by mukulmishra18** [comment]
>  so I guess you are sure that use `decodeURIComponent` instead of `decodeURI` will make the required changes

I think it should solve the problem as `decodeURI` may ignore some of the special characters. But I would suggest to go through the documentations([decodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) and [decodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent)) and read the difference between the two.

> do we need to do something more than this ?

I don't think anything else is required for this issue.

**Comment by shikhar-scs** [comment]
@mukulmishra18  
I tried doing the same, changed the `decodeURI` keyword to `decodeURIComponent`. Then ran `gulp chromium`, added it as an extension to chrome and tried opening a file whose name contained `#` but the `file not found` error persisted.

I had made the changes here
https://github.com/mozilla/pdf.js/blob/237bc2ef9df204069c4996e14433e0a35123444a/src/display/node_stream.js#L368

and here

https://github.com/mozilla/pdf.js/blob/237bc2ef9df204069c4996e14433e0a35123444a/src/display/node_stream.js#L395

Could you please look into it ?

**Comment by mukulmishra18** [comment]
If you try to decode any url that contains `%23` in it, using `decodeURIComponent` then it will decode just fine. So I think this should solve the problem.

Also note that you are using chrome extension, so `node_stream` was never used, because it is intended to use in node environment. I will suggest to create a node app that uses pdf.js and see if problem still persists.

**Comment by shikhar-scs** [comment]
> Also note that you are using chrome extension, so node_stream was never used, because it is intended to use in node environment. I will suggest to create a node app that uses pdf.js and see if problem still persists.

Thank you so much information and also for your help.
