### ISSUE TITLE
Auto-rotate for printing does not work

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#9297]
Attach (recommended) or Link to PDF file here: http://www.co.dutchess.ny.us/CountyGov/Departments/StopDWI/DontBlowIt.pdf

Configuration:
- Web browser and its version: Firefox 57.0.2 (64 bits)
- Operating system and its version: Arch Linux
- PDF.js version: 1.9.583
- Is a browser extension: no (embedded in Firefox)

Steps to reproduce the problem:
1. Enable `pdfjs.enablePrintAutoRotate` in `about:config`.
2. Open the file.
3. Open the print preview.
4. Notice that the landscape pages are not rotated.

What is the expected behavior? (add screenshot)
They should be rotated to fill the entire landscape page.

What went wrong? (add screenshot)
They are sized onto a portrait page.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
-

**Comment by atensoftware** [comment]
This may be the same or related issue.

1. Go to http://www.somacon.com/p352.php
2. Click "Generate calendar" using all the default settings.

Currently, the calendar displays in the browser in "Landscape" orientation, but when the page is printed to a printer, it comes out in Portrait mode.
Instead, Firefox should respect the orientation designated by the PDF and print the page in landscape mode.

This seems to have broken recently because I never got any complaints about it before.
NOTE: The PDF is generated using FPDF to be in landscape orientation--that code hasn't changed.  Also, if I save the PDF to disk and open in Adobe Acrobat Reader, then it correctly prints in Landscape orientation.

Here's my configuration:
Firefox 57.0.2 (64-bit) Win10
Page Setup is configured to print in Portrait mode
pdfjs.enablePrintAutoRotate set to default, which is false.

**Comment by JRC18** [comment]
Just curious if this is ever going to be fixed.  This has always been an issue, but when we could use adobe inside firefox there was a work around.  Every other browser out there can handle this except for Firefox, which makes using in a corporation difficult.

**Comment by sundeepnaga** [comment]
Is this issue is fixed or Not ?

**Comment by mehulbechra** [comment]
@timvandermeij Lets try solving it.

**Comment by sd1998** [comment]
@timvandermeij Is this issue fixed? If not can I work on this?

**Comment by timvandermeij** [comment]
I don't think it's fixed, so if you can reproduce it you can work on this.

**Comment by beijingalex** [comment]
> @timvandermeij这个问题是否已解决？如果没有，我可以解决这个问题吗？

@sd1998 请问你怎么解决这个问题呢。

**Comment by dhuang612** [comment]
Continuing to review into this, and had a question. 
So under firefox_print_services I see canvas.mozPrintCallback = function(obj) {
When I researched more into mozPrintCallback I found that this was an experimental api
Which lead me to the following page:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement
HTMLCanvasElement.mozPrintCallback
Are there docs available anywhere that I can review to learn more about this?
I've only been able to find a gist with a basic implementation 
https://gist.github.com/yurydelendik/4ae793c1c5cdedf8d35b

**Comment by timvandermeij** [comment]
`mozPrintCallback` is only implemented in Firefox and therefore it only exists in the `firefox_print_service.js` file. Its objective is to make a higher resolution rendering of the canvas at the resolution of the printer, so it's essentially an API that helps us to print in higher quality. Unfortunately other browsers never implemented this, nor any other decent printing APIs, so printing from JavaScript is therefore very limited in general.

**Comment by cbj4074** [comment]
It's difficult to believe that this is still an issue, as significant as it is. I have colleagues who report that this has been a problem for at least 8 years.

I guess we'll instruct our customers to use a different browser to download and print our documents... 👎

**Comment by JRC18** [comment]
> It's difficult to believe that this is still an issue, as significant as it is. I have colleagues who report that this has been a problem for at least 8 years.
> I guess we'll instruct our customers to use a different browser to download and print our documents... 👎

Yea, it has been happening as long as I can remember, multiple times tickets are opened then closed with no fix, I'm just glad this one is at least being looked at.  When Adobe could be used inside as an add-on you could hide the issue since Adobe did the functionality, so we had a work around.

**Comment by cdcstl** [comment]
We have the same problem...  And the old web applications can't use Adobe....
Any fix in issue ?

**Comment by ilium007** [comment]
Still an issue, one of the most baffling issues in 20 years of IT. How can this not be resolved after 8 years of reporting? I have had to rollback to Chrome in our organisation because of this.

**Comment by JamieKitson** [comment]
@ilium007 See [my comment on the other issue](https://github.com/mozilla/pdf.js/issues/6696#issuecomment-638078517).

**Comment by ilium007** [comment]
> @ilium007 See [my comment on the other issue](https://github.com/mozilla/pdf.js/issues/6696#issuecomment-638078517).

See my response here: https://github.com/mozilla/pdf.js/issues/6696#issuecomment-638156741

**Comment by JeanMarieMace** [comment]
Hello,

Still have this issue with FireFox 78:

![ff](https://user-images.githubusercontent.com/67750101/88163599-3393f180-cc13-11ea-8f10-8486e3df66cc.PNG)

My pdf page is in landscape (Paysage in french) :
![ff-pdf](https://user-images.githubusercontent.com/67750101/88164143-0431b480-cc14-11ea-9e48-96a8f60e17ea.PNG)

but still printing in portrait , any ideas welcome :)

**Comment by timvandermeij** [comment]
This fix is just merged and not available in Firefox 78 because that released before this fix. It will be in a later Firefox release.

**Comment by JeanMarieMace** [comment]
All right ! Thanks @timvandermeij  ! 
Do you know if there is a "public plan" for that merge ? any ideas of which version/date ?

**Comment by timvandermeij** [comment]
It's most likely going to be in Firefox 80 which is the currently nightly version.

**Comment by stexyn** [comment]
Hallo I use Firefox 81.0.1 (32bit)
Pdf documents landscape in the preview box are not printed in landscape.
I also tried to enable pdfjs.enablePrintAutoRotate but still not work.
Can you help me to fix this please?
Thank you

**Comment by stexyn** [comment]
Hello,
Still have this issue with FireFox 81.0.2

**Comment by tlissak** [comment]
Hello In firefox 85.0
pdfjs.enablePrintAutoRotate in about:config
Do rotate de page automaticly,
This parameter (pdfjs.enablePrintAutoRotate=true ) should be activate by default as other modern browsers.
